<?php

namespace AppartooBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByContact($id)
    {
        $qb = $this->$em->createQueryBuilder();
        $qb->delete('Contact', 'c');
        $qb->andWhere($qb->expr()->eq('c.id', ':id'));
        $qb->setParameter(':id', $id);
    }

}