AppartooBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppartooBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idContact:
            type: integer
            nullable: true
            column: id_contact
    lifecycleCallbacks: {  }

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: maire_id
                referencedColumnName: id
